using AlterNats.Internal;
using System.Buffers;
using System.Collections.Concurrent;

namespace AlterNats;

internal sealed class SubscriptionManager : IDisposable
{
    internal readonly object gate = new object(); // lock for add/remove, publish can avoid lock.
    readonly ConcurrentDictionary<int, RefCountSubscription> bySubscriptionId = new();
    readonly ConcurrentDictionary<string, RefCountSubscription> byStringKey = new();

    internal readonly NatsConnection connection;

    int subscriptionId = 0; // unique alphanumeric subscription ID, generated by the client(per connection).

    public SubscriptionManager(NatsConnection connection)
    {
        this.connection = connection;
    }

    public (int subscriptionId, string subject, NatsKey? queueGroup)[] GetExistingSubscriptions()
    {
        lock (gate)
        {
            return bySubscriptionId.Select(x => (x.Value.SubscriptionId, x.Value.Key, x.Value.QueueGroup)).ToArray();
        }
    }

    public async ValueTask<IDisposable> AddAsync<T>(string key, NatsKey? queueGroup, Action<NatsKey, T> handler)
    {
        int sid;
        RefCountSubscription? subscription;
        int handlerId;

        lock (gate)
        {
            if (byStringKey.TryGetValue(key, out subscription))
            {
                if (subscription.ElementType != typeof(T))
                {
                    throw new InvalidOperationException($"Register different type on same key. Key: {key} RegisteredType:{subscription.ElementType.FullName} NewType:{typeof(T).FullName}");
                }

                handlerId = subscription.AddHandler(handler);
                return new Subscription(subscription, handlerId);
            }
            else
            {
                sid = Interlocked.Increment(ref subscriptionId);

                subscription = new RefCountSubscription(this, sid, key, typeof(T))
                {
                    QueueGroup = queueGroup
                };
                handlerId = subscription.AddHandler(handler);
                bySubscriptionId[sid] = subscription;
                byStringKey[key] = subscription;
            }
        }

        var returnSubscription = new Subscription(subscription, handlerId);
        try
        {
            await connection.SubscribeAsync(sid, key, queueGroup).ConfigureAwait(false);
        }
        catch
        {
            returnSubscription.Dispose(); // can't subscribed, remove from holder.
            throw;
        }

        return returnSubscription;
    }

    public async ValueTask<IDisposable> AddRequestHandlerAsync<TRequest, TResponse>(string key, Func<TRequest, TResponse> handler)
    {
        int sid;
        RefCountSubscription? subscription;
        int handlerId;

        lock (gate)
        {
            if (byStringKey.TryGetValue(key, out subscription))
            {
                if (!subscription.IsRequestHandler)
                {
                    throw new InvalidOperationException($"Already registered not handler. Key: {key}.");
                }

                if (subscription.ElementType != typeof(TRequest) || subscription.ResponseType != typeof(TResponse))
                {
                    throw new InvalidOperationException($"Register different type on same key. Key: {key} RegisteredType: ({subscription.ElementType.FullName},{subscription.ResponseType!.FullName}) NewType: ({typeof(TRequest).FullName}, {typeof(TResponse).FullName}");
                }

                handlerId = subscription.AddHandler(handler);
                return new Subscription(subscription, handlerId);
            }
            else
            {
                sid = Interlocked.Increment(ref subscriptionId);

                subscription = new RefCountSubscription(this, sid, key, typeof(TRequest), typeof(TResponse));
                handlerId = subscription.AddHandler(handler);
                bySubscriptionId[sid] = subscription;
                byStringKey[key] = subscription;
            }
        }

        var returnSubscription = new Subscription(subscription, handlerId);
        try
        {
            await connection.SubscribeAsync(sid, key, null).ConfigureAwait(false);
        }
        catch
        {
            returnSubscription.Dispose(); // can't subscribed, remove from holder.
            throw;
        }

        return returnSubscription;
    }

    public async ValueTask<IDisposable> AddRequestHandlerAsync<TRequest, TResponse>(string key, Func<NatsKey,TRequest, Task<TResponse>> asyncHandler)
    {
        int sid;
        RefCountSubscription? subscription;
        int handlerId;

        lock (gate)
        {
            if (byStringKey.TryGetValue(key, out subscription))
            {
                if (!subscription.IsRequestHandler)
                {
                    throw new InvalidOperationException($"Already registered not handler. Key: {key}.");
                }

                if (subscription.ElementType != typeof(TRequest) || subscription.ResponseType != typeof(TResponse))
                {
                    throw new InvalidOperationException($"Register different type on same key. Key: {key} RegisteredType: ({subscription.ElementType.FullName},{subscription.ResponseType!.FullName}) NewType: ({typeof(TRequest).FullName}, {typeof(TResponse).FullName}");
                }

                handlerId = subscription.AddHandler(asyncHandler);
                return new Subscription(subscription, handlerId);
            }
            else
            {
                sid = Interlocked.Increment(ref subscriptionId);

                subscription = new RefCountSubscription(this, sid, key, typeof(TRequest), typeof(TResponse));
                handlerId = subscription.AddHandler(asyncHandler);
                bySubscriptionId[sid] = subscription;
                byStringKey[key] = subscription;
            }
        }

        var returnSubscription = new Subscription(subscription, handlerId);
        try
        {
            await connection.SubscribeAsync(sid, key, null).ConfigureAwait(false);
        }
        catch
        {
            returnSubscription.Dispose(); // can't subscribed, remove from holder.
            throw;
        }

        return returnSubscription;
    }

    internal void Remove(string key, int subscriptionId)
    {
        // inside lock from RefCountSubscription.RemoveHandler
        byStringKey.Remove(key, out _);
        bySubscriptionId.Remove(subscriptionId, out _);
    }

    public void PublishToClientHandlers(int subscriptionId,in NatsKey subject, in ReadOnlySequence<byte> buffer)
    {
        RefCountSubscription? subscription;
        object?[] list;
        lock (gate)
        {
            if (bySubscriptionId.TryGetValue(subscriptionId, out subscription))
            {
                list = subscription.Handlers.GetValues();
            }
            else
            {
                return;
            }
        }

        MessagePublisher.Publish(subscription.ElementType, subject, connection.Options, buffer, list);
    }

    public void PublishToRequestHandler(int subscriptionId, in NatsKey subject, in NatsKey replyTo, in ReadOnlySequence<byte> buffer)
    {
        RefCountSubscription? subscription;
        object?[] list;
        lock (gate)
        {
            if (bySubscriptionId.TryGetValue(subscriptionId, out subscription))
            {
                if (!subscription.IsRequestHandler)
                {
                    throw new InvalidOperationException($"Registered handler is not request handler.");
                }
                list = subscription.Handlers.GetValues();
            }
            else
            {
                return;
            }
        }

        foreach (var item in list)
        {
            if (item != null)
            {
                RequestPublisher.PublishRequest(subscription.ElementType, subscription.ResponseType!, connection, replyTo, buffer, item);
                return;
            }
        }
    }

    public void Dispose()
    {
        lock (gate)
        {
            // remove all references.
            foreach (var item in bySubscriptionId)
            {
                item.Value.Handlers.Dispose();
            }

            bySubscriptionId.Clear();
            byStringKey.Clear();
        }
    }

    sealed class Subscription : IDisposable
    {
        readonly RefCountSubscription rootSubscription;
        readonly int handlerId;
        bool isDisposed;

        public Subscription(RefCountSubscription rootSubscription, int handlerId)
        {
            this.rootSubscription = rootSubscription;
            this.handlerId = handlerId;
        }

        public void Dispose()
        {
            if (!isDisposed)
            {
                isDisposed = true;
                rootSubscription.RemoveHandler(handlerId);
            }
        }
    }
}

internal sealed class RefCountSubscription
{
    readonly SubscriptionManager manager;

    public int SubscriptionId { get; }
    public string Key { get; }
    public NatsKey? QueueGroup { get; init; }
    public int ReferenceCount { get; private set; }
    public Type ElementType { get; } // or RequestType
    public Type? ResponseType { get; }
    public FreeList<object> Handlers { get; }

    public bool IsRequestHandler => ResponseType != null;

    public RefCountSubscription(SubscriptionManager manager, int subscriptionId, string key, Type elementType)
    {
        this.manager = manager;
        SubscriptionId = subscriptionId;
        Key = key;
        ReferenceCount = 0;
        ElementType = elementType;
        Handlers = new FreeList<object>();
    }

    public RefCountSubscription(SubscriptionManager manager, int subscriptionId, string key, Type requestType, Type responseType)
    {
        this.manager = manager;
        SubscriptionId = subscriptionId;
        Key = key;
        ReferenceCount = 0;
        ElementType = requestType;
        ResponseType = responseType;
        Handlers = new FreeList<object>();
    }

    // Add is in lock(gate)
    public int AddHandler(object handler)
    {
        var id = Handlers.Add(handler);
        ReferenceCount++;
        Interlocked.Increment(ref manager.connection.counter.SubscriptionCount);
        return id;
    }

    public void RemoveHandler(int handlerId)
    {
        lock (manager.gate)
        {
            ReferenceCount--;
            Handlers.Remove(handlerId, false);
            Interlocked.Decrement(ref manager.connection.counter.SubscriptionCount);
            if (ReferenceCount == 0)
            {
                manager.Remove(Key, SubscriptionId);
                Handlers.Dispose();
                manager.connection.PostUnsubscribe(SubscriptionId);
            }
        }
    }
}
